name: mmm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pymc
  - pymc-marketing
  - jupyterlab
  - pandas
  - matplotlib
  - plotly
  - numpy
  - scikit-learn
  - graphviz
  - pip
  - pip:
      - pytimetk
